### PR TITLE
Website Redesign

### PR DESCRIPTION
**Pull request by TymonDomanko**
Basic redesign of website (can color buttons and links if you want)
Demo at http://tymcraft.playat.ch/F32/ (note features don't all work because not clone of full repository)
- Removed calls to die (why would you do this its bad programming(my solution isn't much better but it doesn't kill the whole website)
- Suppressed errors if file retrieval fails
- Added Style-sheet
- Loaded Style-sheet into index.php
- added basic 'style'
  - Made large buttons for main links
  - Made buttons re-size for screen size
- moved git-hub links
- changed credit layout

### CODE REVIEW

**Comment by ghost** [comment]
The die calls was just me being half awake and copy pasting code instead of typing it out like I should. Thanks for fixing that.

I don't have plans for doing older individual mod support so unless that's something someone volunteers to tackle, that button should go.

For the credits section it could be shorter by doing the following. 

Hosting by Greenphlem
Initial design by DZCreeper. 
Improved design by Github Contributors.
Vanilla pack by Vattic.
Modded work by Github Contributors and older third parties.

Where it says Github Contributors, make them hyperlinks to these:

https://github.com/F32Organization/siteF32/graphs/contributors
https://github.com/F32Organization/Faithful32-1.7.10/graphs/contributors

Once this pull request is merged your name will show up there and actually give visual indication of your contribution.

I think we can knock off the 2014 - present portion because neither the site nor the pack is copyrighted by us.

Lastly, I think if the background was a medium to dark gray, buttons light gray, and the text white it would look better than straight black and white. Or maybe keep the text black, light gray background and dark buttons.

Thank you very much for doing this work. If its not too much trouble I would appreciate those minor changes I mentioned. I could do them myself but you are probably better at designing websites than me.

Edit: I fixed the die calls in the running version of the site. That will probably cause your pull request to require a rebase. Sorry about that but I shouldn't leave that kind of issue in the live site.

**Comment by TymonDomanko** [comment]
The Older individual mod support was for when the current mod support was outdated again. Do you still want me to remove it? we could just do "Designed by Github Contributers". yes/no? get rid of the "hosting provided by Greenphlem"? other than sure. Do we have a link to the vanilla pack?

**Comment by ghost** [comment]
Rather than creating another folder for another version of mod support, I plan to merge them all into one folder and label them at some point. I actually already started, just need to find a little bit of time tomorrow.

Yeah, we can just do the Github Contributors thing, my name doesn't need to be displayed. Keep the hosting provided by Greenphlem part though. It takes a decent amount of bandwidth to host the pack and I want to show some appreciation. I do have a link for the vanilla pack but it doesn't really belong on the page, this is Faithful 32 Modded Edition. If you just wanted to make the word 'Vanilla' next to Vattic's name a hyperlink, use this: http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/1223254

**Comment by TymonDomanko** [comment]
i was planning on hyper-linking Vattic's name. Also Should i just create one button for mod support then?
as for style i put together a quick mockup of each of your suggestions:
http://tymcraft.playat.ch/F32/
http://tymcraft.playat.ch/F32/indexb.php
If you want to tell me which you like more we can go from there
will probably change the colors slightly later and make hyperlinks a better color

**Comment by ghost** [comment]
I like the look of the indexb version. I think darkening the buttons just slightly or lightening the background would be good. Leave the separated mod support buttons for now, I will worry about merging them when I have the renaming of the .zip files done which isn't a priority.

Also, the credit section just needs a couple very minor tweaks. Should look like this:

Credit: Hosting provided by Greenphlem. Designed by Github Contributors. Vanilla pack by Vattic. Modded work by Github Contributors and older third parties.

Shouldn't use commas instead of periods, want to differentiate the various types of work done.

**Comment by TymonDomanko** [comment]
So The result of the changes I made can be viewed at:
http://tymcraft.playat.ch/F32/
Also might be looking into SASS to make it easier to change styling if need be(If only CSS had variables  native).

**Comment by TymonDomanko** [comment]
Should be good. Made it a lot easier to recolor all the groups(Buttons, background, text, button text, button outline, hyperlink color etc.).

**Comment by TymonDomanko** [comment]
So I added a page for downloads. They scans a directory and displays all files in it with them as download hyperlinks. They also have a back button. They have the title and credits that I have on the main site. Can be viewed: http://tymcraft.playat.ch/F32/DirectoryScanner.php

Can't think of anything else that needs to be done. Do you want anything else done?

**Comment by ghost** [comment]
While I appreciate the work, I don't really see the point of the downloads page. The site is quite small and future growth isn't going to be large. For the areas large enough to require their download page, the Apache default index setup covers all the basic functionality I need.

If you could separate that into another pull request targeted at the 'downloads' branch I just created, it might be useful at a later date. The remaining stuff is ready to merge, it just needs to be rebased so it will merge. Here is the guide on that if you are new to using Git. https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

There will be a merge conflict because we edited the same file so I suggest commit squashing which is also explained on that page to make resolving the conflict a one time thing.

**Comment by TymonDomanko** [comment]
The idea with the download page is that it looked more professional, you should really never see a default Apache page. But sure I will separate them and figure out how to rebase.

**Pull request closed without merging**
